# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[runner]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'disableStacktrace'
  log-in-console: true

system:
  port: "5080"
etcd:
  endpoints:
    - "http://192.168.123.3:2379"
  username: ""
  password: ""
  root_path: "/simple-cicd/"

